name: Test Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

env:
  APP_VER: Monday
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        id: prepare_app
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
            nn=`ls --time-style='+%Y%m%d' -l ${{ github.workspace }}/apk/*.apk 2>/dev/null |wc -l`
            if [ $nn -gt 0 ]; then  
              ver=`ls --time-style='+%Y%m%d' -l ${{ github.workspace }}/apk/*.apk |head -n 1|awk '{print $6}'`;  
            else 
              ver='release'; 
            fi
            cd ${{ github.workspace }}/apk/
            app_name=`ls *.apk | head -n 1`;  
    
            echo "app_ver=$app_name" >> "$GITHUB_OUTPUT"
            echo "app is: " ${{steps.prepare_app.outputs.app_ver}}
            
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*

      - name: show dir
        run: |
           ls -l ${{ github.workspace }}/apk/${{steps.prepare_app.outputs.app_ver}}

      - name: Release upload
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
             apk/${{steps.prepare_app.outputs.app_ver}}
             
      - name: Upload to release
        uses:  JasonEtco/upload-to-release@master
        with:
          args: apk/${{env.APP_VER}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APP_VER: ${{steps.prepare_app.outputs.app_ver}}

          
