name: Test Build

on:
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --warning-mode all
      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          for file in `find ~ -name "*.apk" -print`; do
            mv "$file" ${{ github.workspace }}/apk/
          done
            ls -l ${{ github.workspace }}/apk/
            nn=`ls --time-style='+%Y%m%d' -l *.apk 2>/dev/null |wc -l`;if [ $nn -gt 0 ]; then  ver=`ls --time-style='+%Y%m%d' -l *.apk |head -n 1|awk '{print $6}'`;  else ver='release'; fi
            tar -zcvf ${{ github.workspace }}/apk/tvbox-takagen99-$ver.gz ${{ github.workspace }}/apk/
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
      
      - name: Upload to release
        uses:  JasonEtco/upload-to-release@master
        with:
          args: ${{ github.workspace }}/apk/tvbox-takagen99-$ver.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
